name: Build And Push Docker

on:
  push:
    branches: [ "gh-action" ]

  workflow_dispatch:

env:
  IMAGE_1: github-actions-deo-act

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Go Build
        run: go build -v ./...

      - name: Go Test
        run: go test ./...
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push hello-text
        id: docker_build_hello-text
        uses: docker/build-push-action@v2
        with:
          context: ./hellotextkubernetes
          file: ./hellotextkubernetes/Dockerfile
          push: true
          tags: ${{ env.IMAGE_1 }}:${{ github.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}